version: "3"

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: testemed
    # volumes:
    #   - ./mysql:/var/lib/mysql
    networks:
      - my-networks
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 30

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
        db:
          condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PASSWORD=12345
      - DB_DATABASE=testemed
    networks:
      - my-networks
    

networks:
  my-networks:
    driver: bridge
